<a href="https://colab.research.google.com/github/disha526/Titanic-Survival-Prediction-Using-Machine-Learning/blob/main/Wine_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basics of pandas


In [71]:
import numpy as n
list =([1,23,3])
array = np.array([1,23,3])
print(array)
print(list)

[ 1 23  3]
[1, 23, 3]


In [72]:
array_a = np.array([1,'b', True])
print(array_a)

['1' 'b' 'True']


In [73]:
array_b = np.array([1,False])
print(array_b)

[1 0]


In [74]:
array_c = np.array(([1,2],[2,34]))
array_c

array([[ 1,  2],
       [ 2, 34]])

In [75]:
array_c = np.array(([1,2],[2,3]) , ndmin =2 )
array_c

array([[1, 2],
       [2, 3]])

In [76]:
list =[1,2,3]
array=np.array([[1,2,3]])
# print(list+1)
print(array+1)

[[2 3 4]]


In [77]:
import random
rand_array1 = np.random.randint(1,5,3)
print(rand_array1)

[3 2 4]


In [78]:
rand_array2 = np.random.randn(5) # normal distribution
print(rand_array2)

[ 1.11317978 -0.31260669  1.07394681 -0.88153805 -0.19392376]


In [79]:
import pandas as pd
s=pd.Series([1,23,34])
s

,0
0,1
1,23
2,34


In [80]:
s = pd.Series([1,2,3,4] , index = ["a","b","c","d"])
s

,0
a,1
b,2
c,3
d,4


In [81]:
df = pd.DataFrame(["disha","ronith","ramya"] , index =[1,2,3], columns =["names"])
df

,names
1,disha
2,ronith
3,ramya


In [82]:
df2 ={"Name":"Disha","USN":"4AL23CG010","Age":"20","COURSE":"CSD"}
s_dict = pd.Series(df2)
s_dict

,0
Name,Disha
USN,4AL23CG010
Age,20
COURSE,CSD


In [83]:
s_list = pd.Series(["blue","green","yellow","red"])
s_list

,0
0,blue
1,green
2,yellow
3,red


In [84]:
s1_list = pd.Series(["blue","green","yellow","red"],index=['a',"b","c","d"])
s1_list

,0
a,blue
b,green
c,yellow
d,red


In [85]:
s2_list =pd.Series(5.0 ,index =[1,2,3,4])
s2_list

,0
1,5.0
2,5.0
3,5.0
4,5.0


In [86]:
data = {"Country":["Belgium","India","Brazil"],
        "Capital":["Brussels","New Delhi","Brasilia"],
        "Population":[111234244,2344444342,5435633]}
df =pd.DataFrame(data,columns=["Country","Capital","Population"])
df


,Country,Capital,Population
0,Belgium,Brussels,111234244
1,India,New Delhi,2344444342
2,Brazil,Brasilia,5435633


In [87]:
data1 = {"a":[1,5],"b":[2,6],"c":[1,2]}
df1 = pd.DataFrame(data1  , columns=["a","b","c"])
df1

,a,b,c
0,1,2,1
1,5,6,2


In [88]:
data_2 = {"one":[1.,2.,3.],
          "two":[2,3,4]
          }

df2 = pd.DataFrame(data_2)
df2


,one,two
0,1.0,2
1,2.0,3
2,3.0,4


In [89]:
data_3 = [{"a":1,"b":3}, {"a":4,"b":3,"c":6}]
df_3 = pd.DataFrame(data_3)
df_3

,a,b,c
0,1,3,NaN
1,4,3,6.0


#Wine_Review

In [92]:
import numpy as np
import pandas as pd

data_set =pd.read_csv("winemag-data-130k-v2.csv")
data_set.head(5)

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks


In [93]:
data_set.columns

Index(['Unnamed: 0', 'country', 'description', 'designation', 'points',
       'price', 'province', 'region_1', 'region_2', 'taster_name',
       'taster_twitter_handle', 'title', 'variety', 'winery'],
      dtype='object')

In [96]:
data_set.shape

(129971, 14)

In [98]:
data_set.dtypes

,0
Unnamed: 0,int64
country,object
description,object
designation,object
points,int64
price,float64
province,object
region_1,object
region_2,object
taster_name,object


In [99]:
type(data_set)

pandas.core.frame.DataFrame